// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdbxdxnieenvprrgexip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkYnhkeG5pZWVudnBycmdleGlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4OTI0MTMsImV4cCI6MjA1NzQ2ODQxM30.wjtmINKBZkzoYDjWRZb3me0QCDJR-ijLo4pAsS-NF1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);